language: python
dist: trusty
python:
    - "3.5"
    - "3.6"
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - pip install coveralls
env:
    matrix:
        - BACKEND=numpy
        - BACKEND=mxnet
        - BACKEND=pytorch
# command to run tests
script:
    - travis_wait make BACKEND=numpy test-coverage
after_success:
    - coveralls
